version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: joke
    ports:
      - "5432:5432"
    volumes:
      - jokes_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test-db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: joketest
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jokes_db_data:
